# Generated by Django 5.2.11 on 2026-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_fetched_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_data_batch_meta',
            },
        ),
        migrations.CreateModel(
            name='PriceFetchCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('has_data', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'market_data_price_fetch_coverage',
                'constraints': [models.UniqueConstraint(fields=('market', 'code', 'date'), name='unique_market_price_coverage')],
            },
        ),
        migrations.CreateModel(
            name='StockDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('is_index', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'market_data_stock_daily_price',
                'constraints': [models.UniqueConstraint(fields=('market', 'code', 'date'), name='unique_market_code_date')],
            },
        ),
        migrations.CreateModel(
            name='StockListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_data_stock_listing',
                'constraints': [models.UniqueConstraint(fields=('market', 'code'), name='unique_market_code')],
            },
        ),
    ]
