# Generated by Django 5.2.11 on 2026-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdailyprice',
            name='market_data_code_c8a24c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockdailyprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockdailyprice',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockdailyprice',
            constraint=models.UniqueConstraint(fields=('code', 'date'), name='unique_code_date'),
        ),
    ]
