# Generated by Django 5.2.11 on 2026-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_remove_stockdailyprice_market_data_code_c8a24c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFetchCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('has_data', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'market_data_price_fetch_coverage',
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='unique_price_coverage')],
            },
        ),
    ]
