# Generated by Django 5.2.11 on 2026-03-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_rename_market_cap_to_listing_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklisting',
            name='listing_shares_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
