# Generated by Django 5.2.11 on 2026-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_pricefetchcoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklisting',
            name='market',
            field=models.CharField(db_index=True, default='KOSPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocklisting',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stocklisting',
            constraint=models.UniqueConstraint(fields=('market', 'code'), name='unique_market_code'),
        ),
    ]
